# =============================================================================
# GKE Standard - Port Forwarding Tasks
# =============================================================================

version: "3"

vars:
  ENV: '{{.ENV | default "develop"}}'
  NAMESPACE: 'odin-std-{{.ENV}}'

tasks:
  ws:
    desc: Port-forward ws-server
    cmds:
      - kubectl port-forward -n {{.NAMESPACE}} svc/odin-ws-server 3005:3001

  gateway:
    desc: Port-forward ws-gateway
    cmds:
      - kubectl port-forward -n {{.NAMESPACE}} svc/odin-ws-gateway 3006:3000

  grafana:
    desc: Port-forward Grafana
    cmds:
      - kubectl port-forward -n {{.NAMESPACE}} svc/odin-monitoring-grafana 3000:3000

  prometheus:
    desc: Port-forward Prometheus
    cmds:
      - kubectl port-forward -n {{.NAMESPACE}} svc/odin-monitoring-prometheus 9090:9090

  provisioning:
    desc: Port-forward provisioning API
    cmds:
      - kubectl port-forward -n {{.NAMESPACE}} svc/odin-provisioning 8082:8082
