{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-tenants
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
data:
  tenants.yaml: |
    tenants:
    {{- range .Values.tenants }}
      - id: {{ .id | quote }}
        name: {{ .name | quote }}
        apps:
        {{- range .apps }}
          - id: {{ .id | quote }}
            name: {{ .name | quote }}
            secret_env: {{ .secret_env | quote }}
        {{- end }}
    {{- end }}
{{- end }}
