{{- if and .Values.enabled .Values.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provisioning.fullname" . }}-admin-token
  labels:
    {{- include "provisioning.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.adminToken | b64enc | quote }}
{{- end }}
