# Default values for publisher subchart

enabled: true

replicaCount: 1

image:
  repository: odin-publisher
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

kafka:
  brokers: "redpanda:9092"

config:
  ratePerSecond: 100
  tokens:
    - BTC
    - ETH
    - SOL
    - DOGE

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
